# Generated by Django 3.0.5 on 2020-04-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('site', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('apelido', models.CharField(max_length=30, unique=True)),
                ('ctps', models.CharField(max_length=30, unique=True)),
                ('dtadmisao', models.DateTimeField(db_column='dtAdmisao')),
                ('salario', models.DecimalField(decimal_places=4, max_digits=19)),
                ('situacao', models.IntegerField(blank=True, null=True)),
                ('imagem', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContasAReceber',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dtvencimento', models.DateField(db_column='dtVencimento')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=19)),
                ('dtcadastro', models.DateTimeField(db_column='dtCadastro')),
            ],
            options={
                'db_table': 'contas_a_receber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoEmailHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contato_email_home_page',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contato_telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailHomePage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('tipoemailhomepage', models.IntegerField(blank=True, db_column='tipoEmailHomePage', null=True)),
                ('principal', models.TextField()),
            ],
            options={
                'db_table': 'email_home_page',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('loja', models.TextField()),
                ('pessoajuridica', models.TextField(db_column='pessoaJuridica')),
                ('situacao', models.IntegerField()),
                ('cnpj', models.CharField(max_length=14)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('razao', models.CharField(max_length=80)),
                ('fantasia', models.CharField(max_length=80)),
                ('cliente', models.TextField()),
                ('fornecedor', models.TextField()),
                ('transportadora', models.TextField()),
                ('dtcadastro', models.DateTimeField(db_column='dtCadastro')),
                ('dtatualizacao', models.DateTimeField(blank=True, db_column='dtAtualizacao', null=True)),
                ('observacoes', models.CharField(blank=True, max_length=1500, null=True)),
                ('limite', models.DecimalField(decimal_places=4, max_digits=19)),
                ('prazo', models.IntegerField()),
                ('prazodiautil', models.TextField(db_column='prazoDiaUtil')),
                ('imunicpipal', models.CharField(blank=True, db_column='iMunicpipal', max_length=15, null=True)),
                ('isuframa', models.CharField(blank=True, db_column='iSuframa', max_length=9, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaCondicoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=19)),
                ('qtdminima', models.IntegerField(db_column='qtdMinima')),
                ('prazo', models.IntegerField()),
                ('bonificacao', models.IntegerField()),
                ('retirada', models.IntegerField()),
                ('desconto', models.DecimalField(decimal_places=4, max_digits=19)),
                ('validade', models.DateField()),
            ],
            options={
                'db_table': 'empresa_condicoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaEmailHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_email_home_page',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaEmpresaProdutoValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_empresa_produto_valor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaInfoReceitaFederal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_info_receita_federal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaInformacaoBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_informacao_bancaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaProdutoValor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bonificacao', models.IntegerField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dias', models.IntegerField()),
                ('qtdminima', models.IntegerField(db_column='qtdMinima')),
                ('validadedesconto', models.DateField(db_column='validadeDesconto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'empresa_produto_valor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('telefonelist_id',
                 models.IntegerField(blank=True, db_column='telefoneList_id', null=True, unique=True)),
            ],
            options={
                'db_table': 'empresa_telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=80, null=True)),
                ('bairro', models.CharField(max_length=50)),
                (
                'pontoreferencia', models.CharField(blank=True, db_column='pontoReferencia', max_length=80, null=True)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('leitura', models.IntegerField(unique=True)),
                ('fechamento', models.IntegerField(blank=True, null=True)),
                ('kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'energia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntradaCte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('tomadorservico', models.IntegerField(blank=True, db_column='tomadorServico', null=True)),
                ('numero', models.CharField(max_length=9)),
                ('serie', models.CharField(max_length=3)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('dtemissao', models.DateField(blank=True, db_column='dtEmissao', null=True)),
                ('vlrcte', models.DecimalField(db_column='vlrCte', decimal_places=4, max_digits=19)),
                ('qtdvolume', models.IntegerField(db_column='qtdVolume')),
                ('pesobruto', models.DecimalField(db_column='pesoBruto', decimal_places=4, max_digits=19)),
                ('vlrfretebruto', models.DecimalField(db_column='vlrFreteBruto', decimal_places=4, max_digits=19)),
                ('vlrtaxas', models.DecimalField(db_column='vlrTaxas', decimal_places=4, max_digits=19)),
                ('vlrcoleta', models.DecimalField(db_column='vlrColeta', decimal_places=4, max_digits=19)),
                ('vlrimpostofrete', models.DecimalField(db_column='vlrImpostoFrete', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'entrada_cte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntradaFiscal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('controle', models.CharField(max_length=13)),
                ('origem', models.CharField(max_length=12)),
                ('vlrdocumento', models.DecimalField(db_column='vlrDocumento', decimal_places=4, max_digits=19)),
                ('vlrtributo', models.DecimalField(db_column='vlrTributo', decimal_places=4, max_digits=19)),
                ('vlrmulta', models.DecimalField(db_column='vlrMulta', decimal_places=4, max_digits=19)),
                ('vlrjuros', models.DecimalField(db_column='vlrJuros', decimal_places=4, max_digits=19)),
                ('vlrtaxa', models.DecimalField(db_column='vlrTaxa', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'entrada_fiscal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntradaNfe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('numero', models.CharField(max_length=9)),
                ('serie', models.CharField(max_length=3)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('dtemissao', models.DateField(blank=True, db_column='dtEmissao', null=True)),
                ('dtentrada', models.DateField(blank=True, db_column='dtEntrada', null=True)),
            ],
            options={
                'db_table': 'entrada_nfe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('situacao', models.IntegerField(blank=True, null=True)),
                ('dtcadastro', models.DateTimeField(blank=True, db_column='dtCadastro', null=True)),
            ],
            options={
                'db_table': 'entrada_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntradaProdutoProduto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=120)),
                ('codigocfop', models.IntegerField(blank=True, db_column='codigoCFOP', null=True)),
                ('lote', models.CharField(max_length=15)),
                ('dtvalidade', models.DateField(blank=True, db_column='dtValidade', null=True)),
                ('qtd', models.IntegerField()),
                ('vlrunitario', models.DecimalField(db_column='vlrUnitario', decimal_places=4, max_digits=19)),
                ('vlrbruto', models.DecimalField(db_column='vlrBruto', decimal_places=4, max_digits=19)),
                ('vlrdesconto', models.DecimalField(db_column='vlrDesconto', decimal_places=4, max_digits=19)),
                ('vlrfrete', models.DecimalField(db_column='vlrFrete', decimal_places=4, max_digits=19)),
                ('vlrimposto', models.DecimalField(db_column='vlrImposto', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'entrada_produto_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaKardex',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dtmovimento', models.DateTimeField(blank=True, db_column='dtMovimento', null=True)),
                ('documento', models.CharField(max_length=44)),
                ('detalhe', models.CharField(max_length=20)),
                ('qtd', models.IntegerField()),
                ('vlrunitario', models.DecimalField(db_column='vlrUnitario', decimal_places=4, max_digits=19)),
                ('qtdentrada', models.IntegerField(db_column='qtdEntrada')),
                ('vlrentrada', models.DecimalField(db_column='vlrEntrada', decimal_places=4, max_digits=19)),
                ('qtdsaida', models.IntegerField(db_column='qtdSaida')),
                ('vlrsaida', models.DecimalField(db_column='vlrSaida', decimal_places=4, max_digits=19)),
                ('saldo', models.IntegerField()),
                ('vlrsaldo', models.DecimalField(db_column='vlrSaldo', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'ficha_kardex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalCestNcm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('segmento', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=600)),
                ('cest', models.CharField(max_length=7)),
                ('ncm', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'fiscal_cest_ncm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalCstOrigem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'fiscal_cst_origem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalFreteSituacaoTributaria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'fiscal_frete_situacao_tributaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalIcms',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscal_icms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalPisCofins',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscal_pis_cofins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalTributosSefazAm',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscal_tributos_sefaz_am',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoReceitaFederal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=70)),
                ('text', models.CharField(max_length=500)),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'info_receita_federal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacaoBancaria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=4)),
                ('agenciadv', models.CharField(blank=True, db_column='agenciaDV', max_length=2, null=True)),
                ('conta', models.CharField(max_length=13)),
                ('contadv', models.CharField(blank=True, db_column='contaDV', max_length=2, null=True)),
                ('tipoconta', models.IntegerField(db_column='tipoConta')),
                ('titularcnpjcpf', models.CharField(db_column='titularCnpjCpf', max_length=14)),
                ('titularnome', models.CharField(db_column='titularNome', max_length=80)),
            ],
            options={
                'db_table': 'informacao_bancaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuPrincipal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=45)),
                ('menulabel', models.CharField(db_column='menuLabel', max_length=45)),
                ('menupai_id', models.IntegerField(db_column='menuPai_id')),
                ('icomenu', models.CharField(blank=True, db_column='icoMenu', max_length=80, null=True)),
                ('tabpane', models.TextField(db_column='tabPane')),
                ('teclaatalho', models.CharField(blank=True, db_column='teclaAtalho', max_length=45, null=True)),
            ],
            options={
                'db_table': 'menu_principal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
                ('capital', models.TextField()),
                ('ibge_codigo', models.CharField(max_length=7)),
                ('ddd', models.IntegerField()),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrcamentoEntrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orcamento', models.TextField()),
            ],
            options={
                'db_table': 'orcamento_entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrcamentoSaida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orcamento', models.TextField()),
            ],
            options={
                'db_table': 'orcamento_saida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('descricao', models.CharField(max_length=120)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=19)),
                ('unidadecomercial', models.IntegerField(db_column='unidadeComercial')),
                ('situacao', models.IntegerField()),
                ('precocompra', models.DecimalField(db_column='precoCompra', decimal_places=4, max_digits=19)),
                ('precovenda', models.DecimalField(db_column='precoVenda', decimal_places=4, max_digits=19)),
                ('varejo', models.IntegerField()),
                ('ultimpostosefaz', models.DecimalField(db_column='ultImpostoSefaz', decimal_places=4, max_digits=19)),
                ('ultfrete', models.DecimalField(db_column='ultFrete', decimal_places=4, max_digits=19)),
                ('comissao', models.DecimalField(decimal_places=4, max_digits=19)),
                ('dtcadastro', models.DateTimeField(db_column='dtCadastro')),
                ('dtatualizacao', models.DateTimeField(blank=True, db_column='dtAtualizacao', null=True)),
                ('nfegenero', models.CharField(db_column='nfeGenero', max_length=2)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True)),
                ('cest', models.CharField(blank=True, max_length=7, null=True)),
                ('imgproduto', models.TextField(blank=True, db_column='imgProduto', null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoCodigoBarra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigobarra', models.CharField(db_column='codigoBarra', max_length=18, unique=True)),
                ('imgcodigobarra', models.TextField(blank=True, db_column='imgCodigoBarra', null=True)),
            ],
            options={
                'db_table': 'produto_codigo_barra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('lote', models.CharField(max_length=15)),
                ('dtvalidade', models.DateField(blank=True, db_column='dtValidade', null=True)),
                ('vlrunitario', models.DecimalField(db_column='vlrUnitario', decimal_places=4, max_digits=19)),
                ('vlrdesconto', models.DecimalField(db_column='vlrDesconto', decimal_places=4, max_digits=19)),
                ('vlrfrete', models.DecimalField(db_column='vlrFrete', decimal_places=4, max_digits=19)),
                ('vlrimposto', models.DecimalField(db_column='vlrImposto', decimal_places=4, max_digits=19)),
                ('dtcadastro', models.DateTimeField(db_column='dtCadastro')),
                ('docentrada', models.CharField(db_column='docEntrada', max_length=15)),
                ('docentradachavenfe', models.CharField(db_column='docEntradaChaveNFe', max_length=44)),
            ],
            options={
                'db_table': 'produto_estoque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoProdutoCodigoBarra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'produto_produto_codigo_barra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoProdutoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'produto_produto_estoque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pagamentosituacao', models.IntegerField(blank=True, db_column='pagamentoSituacao', null=True)),
                ('documento', models.CharField(max_length=18)),
                ('pagamentomodalidade', models.IntegerField(blank=True, db_column='pagamentoModalidade', null=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=19)),
                ('dtpagamento', models.DateField(blank=True, db_column='dtPagamento', null=True)),
                ('dtcadastro', models.DateTimeField(blank=True, db_column='dtCadastro', null=True)),
            ],
            options={
                'db_table': 'recebimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dtcadastro', models.DateTimeField(blank=True, db_column='dtCadastro', null=True)),
                ('dtsaida', models.DateField(db_column='dtSaida')),
            ],
            options={
                'db_table': 'saida_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaidaProdutoNfe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cancelada', models.TextField()),
                ('chave', models.CharField(max_length=47, unique=True)),
                ('statussefaz', models.IntegerField(blank=True, db_column='statusSefaz', null=True)),
                ('naturezaoperacao', models.IntegerField(blank=True, db_column='naturezaOperacao', null=True)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('serie', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('dthoraemissao', models.DateTimeField(db_column='dtHoraEmissao')),
                ('dthorasaida', models.DateTimeField(db_column='dtHoraSaida')),
                ('destinooperacao', models.IntegerField(blank=True, db_column='destinoOperacao', null=True)),
                ('impressaotpimp', models.IntegerField(blank=True, db_column='impressaoTpImp', null=True)),
                ('impressaotpemis', models.IntegerField(blank=True, db_column='impressaoTpEmis', null=True)),
                ('impressaofinnfe', models.IntegerField(blank=True, db_column='impressaoFinNFe', null=True)),
                ('consumidorfinal', models.IntegerField(blank=True, db_column='consumidorFinal', null=True)),
                ('indicadorpresenca', models.IntegerField(blank=True, db_column='indicadorPresenca', null=True)),
                ('modfrete', models.IntegerField(blank=True, db_column='modFrete', null=True)),
                ('cobrancanumero', models.CharField(db_column='cobrancaNumero', max_length=10)),
                ('pagamentoindicador', models.IntegerField(blank=True, db_column='pagamentoIndicador', null=True)),
                ('pagamentomeio', models.IntegerField(blank=True, db_column='pagamentoMeio', null=True)),
                ('informacaoadicional', models.CharField(db_column='informacaoAdicional', max_length=5000)),
                ('digval', models.CharField(blank=True, db_column='digVal', max_length=28, null=True, unique=True)),
                ('xmlassinatura', models.TextField(blank=True, db_column='xmlAssinatura', null=True)),
                ('xmlprotnfe', models.TextField(blank=True, db_column='xmlProtNfe', null=True)),
            ],
            options={
                'db_table': 'saida_produto_nfe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaidaProdutoProduto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=120)),
                ('codigocfop', models.IntegerField(blank=True, db_column='codigoCFOP', null=True)),
                ('lote', models.CharField(blank=True, max_length=15, null=True)),
                ('dtvalidade', models.DateField(blank=True, db_column='dtValidade', null=True)),
                ('qtd', models.IntegerField()),
                ('vlrentrada', models.DecimalField(db_column='vlrEntrada', decimal_places=4, max_digits=19)),
                ('vlrentradabruto', models.DecimalField(db_column='vlrEntradaBruto', decimal_places=4, max_digits=19)),
                ('vlrunitario', models.DecimalField(db_column='vlrUnitario', decimal_places=4, max_digits=19)),
                ('vlrbruto', models.DecimalField(db_column='vlrBruto', decimal_places=4, max_digits=19)),
                ('vlrdesconto', models.DecimalField(db_column='vlrDesconto', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'saida_produto_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=11)),
                ('principal', models.TextField()),
            ],
            options={
                'db_table': 'telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefoneOperadora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codwsportabilidade',
                 models.CharField(blank=True, db_column='codWSPortabilidade', max_length=5, null=True)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'telefone_operadora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'uf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id',
                 models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                      serialize=False, to='cafeperfeito.Colaborador')),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=128)),
                ('accessguest', models.IntegerField(db_column='accessGuest')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
