# Generated by Django 2.1.5 on 2019-01-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cafeperfeito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoEmailhomepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contato_emailHomePage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contato_telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emailhomepage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'emailHomePage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaEmailhomepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_emailHomePage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaInforeceitafederal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_infoReceitaFederal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalcestncm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('segmento', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=600)),
                ('cest', models.CharField(max_length=7)),
                ('ncm', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'fiscalCestNcm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalcstorigem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'fiscalCstOrigem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalfretesituacaotributaria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'fiscalFreteSituacaoTributaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalicms',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscalIcms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalpiscofins',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscalPisCofins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscaltributossefazam',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscalTributosSefazAm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HibernateSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_val', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hibernate_sequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inforeceitafederal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('code', models.CharField(max_length=70)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'infoReceitaFederal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('descricao', models.CharField(max_length=120)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=19)),
                ('unidadecomercial', models.IntegerField(db_column='unidadeComercial')),
                ('situacao', models.IntegerField()),
                ('precofabrica', models.DecimalField(db_column='precoFabrica', decimal_places=2, max_digits=19)),
                ('precoconsumidor', models.DecimalField(db_column='precoConsumidor', decimal_places=2, max_digits=19)),
                ('varejo', models.IntegerField()),
                ('ultimpostosefaz', models.DecimalField(db_column='ultImpostoSefaz', decimal_places=2, max_digits=19)),
                ('ultfrete', models.DecimalField(db_column='ultFrete', decimal_places=2, max_digits=19)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True)),
                ('cest', models.CharField(blank=True, max_length=7, null=True)),
                ('nfegenero', models.CharField(blank=True, db_column='nfeGenero', max_length=255, null=True)),
                ('datacadastro', models.DateTimeField(db_column='dataCadastro')),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='dataAtualizacao', null=True)),
                ('imgproduto', models.TextField(blank=True, db_column='imgProduto', null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtocodigobarra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigobarra', models.CharField(db_column='codigoBarra', max_length=13, unique=True)),
                ('imgcogigobarra', models.TextField(blank=True, db_column='imgCogigoBarra', null=True)),
            ],
            options={
                'db_table': 'produtoCodigoBarra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoProdutocodigobarra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'produto_produtoCodigoBarra',
                'managed': False,
            },
        ),
    ]
