# Generated by Django 2.1.5 on 2019-02-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('apelido', models.CharField(max_length=30)),
                ('ctps', models.CharField(max_length=30)),
                ('dataadmisao', models.DateTimeField(blank=True, db_column='dataAdmisao', null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ativo', models.TextField()),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoEmailhomepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contato_emailHomePage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contato_telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emailhomepage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'emailHomePage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lojasistema', models.TextField(db_column='lojaSistema')),
                ('classifjuridica', models.IntegerField(db_column='classifJuridica')),
                ('cnpj', models.CharField(max_length=14)),
                ('ieisento', models.TextField(db_column='ieIsento')),
                ('ie', models.CharField(max_length=14)),
                ('razao', models.CharField(max_length=80)),
                ('fantasia', models.CharField(max_length=80)),
                ('cliente', models.TextField()),
                ('fornecedor', models.TextField()),
                ('transportadora', models.TextField()),
                ('situacao', models.IntegerField()),
                ('datacadastro', models.DateTimeField(blank=True, db_column='dataCadastro', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='dataAtualizacao', null=True)),
                ('dataabetura', models.DateTimeField(blank=True, db_column='dataAbetura', null=True)),
                ('naturezajuridica', models.CharField(db_column='naturezaJuridica', max_length=150)),
                ('observacoes', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaEmailhomepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_emailHomePage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaInforeceitafederal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_infoReceitaFederal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=50)),
                ('prox', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalcestncm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('segmento', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=600)),
                ('cest', models.CharField(max_length=7)),
                ('ncm', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'fiscalCestNcm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalcstorigem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'fiscalCstOrigem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalfretesituacaotributaria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'fiscalFreteSituacaoTributaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalicms',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscalIcms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscalpiscofins',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscalPisCofins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscaltributossefazam',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fiscalTributosSefazAm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HibernateSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_val', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hibernate_sequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inforeceitafederal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('code', models.CharField(max_length=70)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'infoReceitaFederal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menuprincipal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=45)),
                ('menulabel', models.CharField(db_column='menuLabel', max_length=45)),
                ('menupai_id', models.IntegerField(db_column='menuPai_id')),
                ('tabpane', models.TextField(db_column='tabPane')),
                ('icomenu', models.CharField(blank=True, db_column='icoMenu', max_length=80, null=True)),
                ('teclaatalho', models.CharField(blank=True, db_column='teclaAtalho', max_length=45, null=True)),
            ],
            options={
                'db_table': 'menuPrincipal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
                ('ibge_codigo', models.CharField(max_length=7)),
                ('ddd', models.IntegerField()),
                ('capital', models.TextField()),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('descricao', models.CharField(max_length=120)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=19)),
                ('unidadecomercial', models.IntegerField(db_column='unidadeComercial')),
                ('situacao', models.IntegerField()),
                ('precofabrica', models.DecimalField(db_column='precoFabrica', decimal_places=2, max_digits=19)),
                ('precoconsumidor', models.DecimalField(db_column='precoConsumidor', decimal_places=2, max_digits=19)),
                ('varejo', models.IntegerField()),
                ('ultimpostosefaz', models.DecimalField(db_column='ultImpostoSefaz', decimal_places=2, max_digits=19)),
                ('ultfrete', models.DecimalField(db_column='ultFrete', decimal_places=2, max_digits=19)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True)),
                ('cest', models.CharField(blank=True, max_length=7, null=True)),
                ('nfegenero', models.CharField(blank=True, db_column='nfeGenero', max_length=255, null=True)),
                ('datacadastro', models.DateTimeField(db_column='dataCadastro')),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='dataAtualizacao', null=True)),
                ('imgproduto', models.TextField(blank=True, db_column='imgProduto', null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtocodigobarra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigobarra', models.CharField(db_column='codigoBarra', max_length=13, unique=True)),
                ('imgcogigobarra', models.TextField(blank=True, db_column='imgCogigoBarra', null=True)),
            ],
            options={
                'db_table': 'produtoCodigoBarra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoProdutocodigobarra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'produto_produtoCodigoBarra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefoneoperadora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('tipo', models.IntegerField()),
                ('ddd', models.IntegerField()),
                ('codwsportabilidade',
                 models.CharField(blank=True, db_column='codWsPortabilidade', max_length=30, null=True)),
            ],
            options={
                'db_table': 'telefoneOperadora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'uf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id',
                 models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                      serialize=False, to='ftpcafeperfeito.Colaborador')),
                ('email', models.CharField(max_length=120)),
                ('senha', models.CharField(max_length=60)),
                ('imagem', models.TextField(blank=True, null=True)),
                ('userativo', models.IntegerField(blank=True, db_column='userAtivo', null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
