# Generated by Django 2.1.5 on 2019-02-07 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ftpcafeperfeito', '0002_auto_20190206_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_nome',
            new_name='menu_label',
        ),
    ]
