# Generated by Django 2.1.5 on 2019-02-07 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ftpcafeperfeito', '0005_auto_20190206_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='menuprincipal',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
