# Generated by Django 2.1.5 on 2019-02-07 16:18

import django.db.models.deletion
import treewidget.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ftpcafeperfeito', '0009_auto_20190207_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menutree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('menu_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='ftpcafeperfeito.Menuprincipal')),
                ('parent',
                 treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='children', to='ftpcafeperfeito.Menutree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
