# Generated by Django 2.1.5 on 2019-02-09 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ftpcafeperfeito', '0011_auto_20190208_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
