# Generated by Django 2.1.7 on 2019-02-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ftpcafeperfeito', '0012_auto_20190208_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
