# Generated by Django 2.1.7 on 2019-02-12 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ftpcafeperfeito', '0013_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
